linters:
  enable:
    - copyloopvar
    - errorlint
    - exhaustive
    - gofumpt
    - goimports
    - gosec
    - lll
    - mnd
    - nolintlint
    - revive
    - stylecheck
    - wrapcheck

linters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/frozenbonito/unisrv
  stylecheck:
    checks:
      - all

issues:
  include:
    - EXC0012
    - EXC0013
    - EXC0014
  max-issues-per-linter: 0
  max-same-issues: 0
