version: 2
project_name: unisrv
builds:
  - main: ./cmd/unisrv
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs(\\(.*\\))?!?:"
      - "^test(\\(.*\\))?!?:"
      - "^chore(\\(.*\\))?!?:"
      - "^Merge pull request"
archives:
  - format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
      - frozenbonito/unisrv:latest-amd64
      - frozenbonito/unisrv:{{ .Version }}-amd64
      - frozenbonito/unisrv:{{ .Major }}-amd64
      - frozenbonito/unisrv:{{ .Major }}.{{ .Minor }}-amd64
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      - frozenbonito/unisrv:latest-arm64
      - frozenbonito/unisrv:{{ .Version }}-arm64
      - frozenbonito/unisrv:{{ .Major }}-arm64
      - frozenbonito/unisrv:{{ .Major }}.{{ .Minor }}-arm64
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm64
docker_manifests:
  - name_template: frozenbonito/unisrv:latest
    image_templates:
      - frozenbonito/unisrv:latest-amd64
      - frozenbonito/unisrv:latest-arm64
  - name_template: frozenbonito/unisrv:{{ .Version }}
    image_templates:
      - frozenbonito/unisrv:{{ .Version }}-amd64
      - frozenbonito/unisrv:{{ .Version }}-arm64
  - name_template: frozenbonito/unisrv:{{ .Major }}
    image_templates:
      - frozenbonito/unisrv:{{ .Major }}-amd64
      - frozenbonito/unisrv:{{ .Major }}-arm64
  - name_template: frozenbonito/unisrv:{{ .Major }}.{{ .Minor }}
    image_templates:
      - frozenbonito/unisrv:{{ .Major }}.{{ .Minor }}-amd64
      - frozenbonito/unisrv:{{ .Major }}.{{ .Minor }}-arm64
